create database telecom;
use telecom;
show tables;
select * from churn;
desc churn;

-- TOTAL CUSTOMER COUNT
SELECT
DISTINCT COUNT(customer_id) AS Customer_count
FROM churn;

-- CUSTOMER COUNT BY GENDER
SELECT
COUNT(*) AS Customers,
Gender
FROM churn 
GROUP BY Gender;

-- CUSTOMERS BY AGE GROUP
SELECT
COUNT(*) AS Customers,
age_group
FROM churn 
GROUP BY age_group
ORDER BY age_group;

-- CUSTOMER COUNT BY MARRIED STATUS
SELECT
COUNT(*) AS Customers,
married
FROM churn 
GROUP BY married;

-- COUNT OF CUSTOMERS BY STATUS
SELECT
COUNT(*) AS Customers,
customer_status
FROM churn 
GROUP BY customer_status
ORDER BY customer_status;

-- COUNT OF CUSTOMERS BY CONTRACT BASE
SELECT
COUNT(*) AS Customers,
contract
FROM churn 
GROUP BY contract
ORDER BY contract;

-- DISTINCT CITYS OF CUSTOMERS
SELECT
DISTINCT city 
FROM churn;

-- CUSTOMER COUNT BY PAYMENT METHOD
SELECT
COUNT(*) AS Customers,
payment_method
FROM churn 
GROUP BY payment_method
ORDER BY payment_method;

-- COUNT OF PREMIUM TECH CUSTOMER AND NOT
SELECT
COUNT(*) AS Customers,
premium_tech_support
FROM churn
GROUP BY premium_tech_support;



-- CHURN ANALYSIS BASED ON DIFFERENT SEGMENTS

-- COUNT OF CHURNED CUSTOMERS
SELECT
COUNT(*) AS CHURNED_CUSTOMER
FROM churn
WHERE customer_status = 'churned';

-- COUNT OF CHURNED CUSTOMERS BASED ON REASON
SELECT
COUNT(*) AS CHURNED_CUSTOMER,
churn_reason
FROM churn
WHERE customer_status = 'churned'
GROUP BY churn_reason 
ORDER BY CHURNED_CUSTOMER DESC;

-- COUNT OF CHURNED CUSTOMER BASED ON CHURN CATEGORY
SELECT
COUNT(*) AS CHURNED_CUSTOMER,
churn_category
FROM churn
WHERE customer_status = 'churned'
GROUP BY churn_category 
ORDER BY CHURNED_CUSTOMER DESC;

-- COUNT OF CHURNED CUSTOMER BY CONTRACT BASE
SELECT
COUNT(*) AS CHURNED_CUSTOMER,
contract
FROM churn
WHERE customer_status = 'churned'
GROUP BY contract 
ORDER BY CHURNED_CUSTOMER DESC;

-- FINANCIAL ANALYSIS LIKE REVENUE,COST,REFUND ETC

SELECT
SUM(total_revenue) AS TOTAL_REVENUE,
SUM(total_charges) AS TOTAL_CHARGES,
SUM(total_refunds) AS TOTAL_REFUNDS
FROM churn;

-- REVENUE GENERATED BY CHURNED CUSTOMERS
SELECT
SUM(total_revenue) AS TOTAL_REVENUE
FROM churn
WHERE customer_status = 'Churned';

-- CUSTOMERS COUNT BY OFFERS PROVIDED
SELECT
COUNT(*) AS Customers,
offer
FROM churn
GROUP BY offer
ORDER BY offer;

-- COUNT OF CHURNED CUSTOMER BASED ON OFFERS
SELECT
COUNT(*) AS Customers,
offer
FROM churn
WHERE customer_status='churned'
GROUP BY offer
ORDER BY offer;

-- TOP 5 REASONS FOR CHURN

WITH REASON AS
(
SELECT 
churn_reason,
COUNT(customer_id) AS TOTAL_CUSTOMER
FROM churn
WHERE customer_status ='churned'
GROUP BY churn_reason
ORDER BY TOTAL_CUSTOMER DESC)

SELECT
churn_reason,
TOTAL_CUSTOMER,
RANK() OVER (ORDER BY TOTAL_CUSTOMER DESC )  AS RANKX
FROM REASON
LIMIT 5;




 

 
 